[package]
name = "cellular"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.29.2"
rand = "0.8.5"
tracing = { version = "0.1.41", optional = true }

[features]
default = []
trace = ["tracing"]
